### ISSUE TITLE
Enlace creación con GUI

### ISSUE THREAD

**Issue by jaimepaine** [jaimepaine/laboratorio#1]
Enlazar crear nuevo cheque  con la gui de libro de cheque

**Comment by juanDemo** [comment]
Eliminar Cheque::: 
    MediadorChequesGui.java
        boolen elminarCheque(Long idCheque) // retorna false si no se pudo guardar

**Comment by juanDemo** [comment]
Refrescar Tabla Libro de Cheques::
LibroChequeGui.java
void refrescarTablas()

**Comment by juanDemo** [comment]
Cheque Rebotado::
MeduiadorChequesGui.java
boolean renotarCheque(Long idCheque) //retorna false si no se puedo rebotar el cheque 
hay que ejecutar despues de este metodo cargarTablas() en la gui

**Comment by jaimepaine** [comment]
Corrección al Eliminar y Rebotar cheque en el caso que el método retorne false. Agregue un aviso cuando el cheque se elimina o se rebota en forma correcta.

**Comment by juanDemo** [comment]
Me parece que ya esta echo
