### ISSUE TITLE
Probar eliminar cheque 

### ISSUE THREAD

**Issue by juanDemo** [jaimepaine/laboratorio#13]
probar si efectivamente elimina el cheque y si lo elimina a pesar de estar asociado a una cuenta o pago.

**Comment by jaimepaine** [comment]
Por ahora graficamente lo elimina bien al cheque seleccionado. :+1:

**Comment by juanDemo** [comment]
Hay un bug, no se debe permitir eliminar si el cheque esta todavía asociado a una cuenta. (Solucionado)

**Comment by jaimepaine** [comment]
Solucionado y chequeado.
