### ISSUE TITLE
Faltan comentarios inferiores en botones de GUI libro cheques

### ISSUE THREAD

**Issue by juanDemo** [jaimepaine/laboratorio#15]
El boton recargar tiene comentario de guardar nuevo cheque, el botón eliminar y rebotar cheque no tienen comentario cuando uno pasa el mouse. son muy utiles ya que pueden olvidarse que hace cada botón y seguramente llamaran para que le agreguemos lo comentarios.

**Comment by jaimepaine** [comment]
listo
