### ISSUE TITLE
Busqueda por chque rebotado

### ISSUE THREAD

**Issue by juanDemo** [jaimepaine/laboratorio#19]
Solo se trata de buscar en Observaciones que comience con ¡REBOTADO! en la gui

**Comment by jaimepaine** [comment]
Una pregunta, esta búsqueda seria buscar primero todos los cheques rebotados y después sobre esa búsqueda buscar por nombre de cliente o por fecha o por rango de fechas?

**Comment by jaimepaine** [comment]
O sólo seria buscar todos los cheques rebotados, sin importar nada mas?

**Comment by jaimepaine** [comment]
por ahora lo hice con un checkbox y busca todos los cheques rebotados.
