### ISSUE TITLE
Eliminar cheque seleccionado

### ISSUE THREAD

**Issue by jaimepaine** [jaimepaine/laboratorio#2]
Agregar funcionalidad eliminar cheque seleccionado. (no hay nada echo agregar boton)

**Comment by jaimepaine** [comment]
Consulta. Al seleccionar un cheque y posteriormente apretar el botón ELIMINAR no deberiamos pedirle una confirmación para saber si realmente quiere eliminarlo o apretó el botón por error? por ahora esta hecho como eliminación directa :)

**Comment by juanDemo** [comment]
Si tal cual un cartel que le avise con aceptar y cancelar
