### ISSUE TITLE
Agregar botón y funcionalidad en Libro Cheques (Salida de Cheque)

### ISSUE THREAD

**Issue by juanDemo** [jaimepaine/laboratorio#24]
Un cheque puede tener salida por que se endoso a alguien o se deposito en algún banco
GUI: 
-Insertar nuevo botón que (con imagen de salida puede ser un flecha cin un papel o un sobre algo asi)  indique salida de cheque.
-Abrir dialogo o nueva ventana según convenga (Salida Cheque). Tiene que mostrar los siguentes datos del cheque (Librador, fecha de entrada, banco, numero de cheque, saldo) no se debe permitir modificar en la gui estos datos. Ademas debe contener un check box opciones: - endosar (Modifica Campo endosoA) mostrar un textbox que modifica endosaA, o -depositar en: modifica banco destino. Y Ademas debe permitir ingresar la fecha de salida.
-Controles no permitir salida de cheque si el cheque tiene endosoA o BancoDestino.

Logica:
- Brindar los métodos neceserarios para modificar en la base de datos endosoA y Banco Destino

**Comment by juanDemo** [comment]
No se debe permitir esta funcionalidad para los cheques que esten en el histrorial por lo que el botón debe estar desactivado si esta seleccionada la solapa del historial

**Comment by juanDemo** [comment]
Esta lista la parte de la logica queda probar
Metodo en MediadorLibroCheque
 boolean:DarSalidaCheque(idCheque,endosaA,comentario)
falta probar :)

**Comment by jaimepaine** [comment]
- Se agrego boton para Salida de Cheque
- Creacion de interfaz grafica.
- Falta unir con funciones logicas, queda para mas tarde jeje

**Comment by jaimepaine** [comment]
CONSULTA:
en la función boolean:DarSalidaCheque(idCheque,endosaA,bancoDestino,comentario)
el parámetro "comentario" debería ser una caja de texto en la interfaz salida de cheque no?
idCheque el id del cheque a modificar
endosaA el endoso de la caja de texto 
bancoDestino el bando destino de la caja texto
comentario: es un comentario extra que agrega  a los comentarios del cheque

**Comment by jaimepaine** [comment]
CONSULTA2:
la función DarSalidaCheque, al dar salida a un cheque en forma exitosa, no debería enviar el mismo al historial y quitarlo de la pestaña "Para Depositar/ Entregar"? O solo le agrega el comentario anterior y le cambia los parámetros ya sea "Banco Destino" o "Endoso a"?

Tal Cual es así esta faltanto esto, de todas formas hay que preguntarle al cliente.

**Comment by jaimepaine** [comment]
- Detalles graficos Finalizados(controles campos, etc).
- Unión con Logica realizada.
  *\* queda revisar las dos consultas anteriores

**Comment by juanDemo** [comment]
Falta la imagen en el svn del botón por lo que da error,al hacer update y ejecutar el libro de cheque

**Comment by juanDemo** [comment]
Esta Lista
