### ISSUE TITLE
Excepciones en algunas busquedas GUI

### ISSUE THREAD

**Issue by juanDemo** [jaimepaine/laboratorio#26]
cuando se realiza algunas busquedas se lanzan excepciones aunque la funcionalidad esta funcionando

**Comment by jaimepaine** [comment]
que tipo de búsqueda te hacían lanzar excepciones?
Xq realice varias y ninguna me tiro ni una excepción.

**Comment by juanDemo** [comment]
No recuerdo bien , ahora probando de nuevo no salta por lo que demos de vaja a esta issue y de alta si vuelve a saltar
