### ISSUE TITLE
Orden en Libro de Cheques

### ISSUE THREAD

**Issue by jaimepaine** [jaimepaine/laboratorio#34]
Se podría cambiar el orden de la vista de libro de cheques y ordenarlos por fecha de entrada por defecto? O está puesto asi por alguna razón particular?

**Comment by juanDemo** [comment]
calculo que quedo ordenado por id, no se pidió en la charla. Seguramente se podria dar ordenado donde  el mas actual este en el tope de la tabla. Habrai que ver si se puede hacer directamente de la gui. O ver si desde el manejador de persistencia se puede hacer esto.

**Comment by jaimepaine** [comment]
a entonces lo puedo cambiar, eso se hace desde la gui nomas.

**Comment by jaimepaine** [comment]
a entonces lo puedo cambiar, eso se hace desde la gui nomas.

**Comment by juanDemo** [comment]
Meta No mas si tiene ganas asi este sabado hacemos la instalación en el laboratorio

**Comment by jaimepaine** [comment]
Listo, orden establecido.
