### ISSUE TITLE
Modificar agregar cheque

### ISSUE THREAD

**Issue by jaimepaine** [jaimepaine/laboratorio#7]
Agregar funcionalidad a agregar cheque (Ver que esta echo y que agregar en la gui)

**Comment by juanDemo** [comment]
Se agrego en el MedidadorLibroCequesGUI.java el metodo guardarNuevoCheque(...) , para guardar el nuevo cheque

**Comment by jaimepaine** [comment]
Pregunta....MediadorLibroChequesGUI reemplazaría a la ChequeControlador no?

**Comment by juanDemo** [comment]
creo que si che
